name: inkozi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 5.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  webview_flutter: ^4.4.2
  flutter_svg: ^2.0.7  
  http: ^1.1.0
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  location: 
  google_maps_flutter: ^2.5.0
  # geolocator: ^10.1.0
  permission_handler: 
  shared_preferences: ^2.2.2
  geocoding:
  # firebase_core: ^2.16.0
  # firebase_auth: ^4.10.0
  # cloud_firestore: 
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get: ^4.6.6
  dio:
  url_launcher: 
  dropdown_button2: ^2.3.9
  change_app_package_name: ^1.1.0
  video_player: ^2.7.0
  socket_io_client: ^1.0.0
  



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  grouped_list: ^5.1.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logocolor.png"


  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  

  # To add assets to your application, add an assets section, like this:


  assets:
    - assets/
    - assets/images/
    - assets/icons/


  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 400
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 700



  uses-material-design: true

